name: BPML
channels:
  - pytorch
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - mne
  - pyedflib
  - yasa
  - pytorch=2.5.*
  - torchvision
  - torchaudio
  - cpuonly

  - pip
  - pip:
      - gssc
      - dtcwt