name: BPML
channels:
  - pytorch
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11

  # Core scientific stack
  - numpy>=1.24, <2.0
  - numba>=0.59, <0.61 # Pinned to match numpy <2.0
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - openpyxl 
  - xggboost

  # Sleep/EDF tooling
  - mne
  - pyedflib
  - yasa

  # PyTorch pinned for GSSC compatibility
  - pytorch=2.5.*
  - torchvision
  - torchaudio
  - cpuonly

  - pip
  - pip:
      - dtcwt
      - art